name: Build

on:
  push:
    branches: [ "pushing-image-to-registry" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: SQLX_OFFLINE=true cargo build --verbose
      - name: Run tests
        run: SQLX_OFFLINE=true cargo test --verbose
      - name: check files
        run: pwd && ls
      - name: Checking docker file
        run: docker build --check . --file Dockerfile
  docker-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} ## This needs a GH token on our environment
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest 
# Think about how we need to push tagging
# If we want automatic tagging
# Else we trigger it on the git tag push origin
