name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: SQLX_OFFLINE=true cargo build --verbose
    - name: Run tests
      run: SQLX_OFFLINE=true cargo test --verbose
